config/routes.rb
Management::Application.routes.draw do
  resources :clients

end

app/models/client.rb
class Client < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render action: 'show', status: :created, location: @client }
      else
        format.html { render action: 'new' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:first_name, :middle_name, :last_name, :suffix_name, :date_of_birth, :age, :ssn, :adult, :gender, :county, :citizen, :marital_status, :supervision_level_id, :risk_level_id, :sid_number, :fbi_number, :oid_number, :afis_number, :ins_number, :email_address, :dna_status_id, :dna_effective_date, :supervision_sheet, :client_label, :drivers_license_number, :drivers_license_state_id, :supervising_location, :supervising_county, :client_status_id, :effective_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :middle_name %><br>
    <%= f.text_field :middle_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :suffix_name %><br>
    <%= f.text_field :suffix_name %>
  </div>
  <div class="field">
    <%= f.label :date_of_birth %><br>
    <%= f.date_select :date_of_birth %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :ssn %><br>
    <%= f.text_field :ssn %>
  </div>
  <div class="field">
    <%= f.label :adult %><br>
    <%= f.check_box :adult %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :county %><br>
    <%= f.text_field :county %>
  </div>
  <div class="field">
    <%= f.label :citizen %><br>
    <%= f.check_box :citizen %>
  </div>
  <div class="field">
    <%= f.label :marital_status %><br>
    <%= f.text_field :marital_status %>
  </div>
  <div class="field">
    <%= f.label :supervision_level_id %><br>
    <%= f.number_field :supervision_level_id %>
  </div>
  <div class="field">
    <%= f.label :risk_level_id %><br>
    <%= f.number_field :risk_level_id %>
  </div>
  <div class="field">
    <%= f.label :sid_number %><br>
    <%= f.text_field :sid_number %>
  </div>
  <div class="field">
    <%= f.label :fbi_number %><br>
    <%= f.text_field :fbi_number %>
  </div>
  <div class="field">
    <%= f.label :oid_number %><br>
    <%= f.text_field :oid_number %>
  </div>
  <div class="field">
    <%= f.label :afis_number %><br>
    <%= f.text_field :afis_number %>
  </div>
  <div class="field">
    <%= f.label :ins_number %><br>
    <%= f.text_field :ins_number %>
  </div>
  <div class="field">
    <%= f.label :email_address %><br>
    <%= f.text_field :email_address %>
  </div>
  <div class="field">
    <%= f.label :dna_status_id %><br>
    <%= f.number_field :dna_status_id %>
  </div>
  <div class="field">
    <%= f.label :dna_effective_date %><br>
    <%= f.date_select :dna_effective_date %>
  </div>
  <div class="field">
    <%= f.label :supervision_sheet %><br>
    <%= f.check_box :supervision_sheet %>
  </div>
  <div class="field">
    <%= f.label :client_label %><br>
    <%= f.check_box :client_label %>
  </div>
  <div class="field">
    <%= f.label :drivers_license_number %><br>
    <%= f.text_field :drivers_license_number %>
  </div>
  <div class="field">
    <%= f.label :drivers_license_state_id %><br>
    <%= f.number_field :drivers_license_state_id %>
  </div>
  <div class="field">
    <%= f.label :supervising_location %><br>
    <%= f.text_field :supervising_location %>
  </div>
  <div class="field">
    <%= f.label :supervising_county %><br>
    <%= f.text_field :supervising_county %>
  </div>
  <div class="field">
    <%= f.label :client_status_id %><br>
    <%= f.number_field :client_status_id %>
  </div>
  <div class="field">
    <%= f.label :effective_date %><br>
    <%= f.date_select :effective_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<h1>Listing clients</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Middle name</th>
      <th>Last name</th>
      <th>Suffix name</th>
      <th>Date of birth</th>
      <th>Age</th>
      <th>Ssn</th>
      <th>Adult</th>
      <th>Gender</th>
      <th>County</th>
      <th>Citizen</th>
      <th>Marital status</th>
      <th>Supervision level</th>
      <th>Risk level</th>
      <th>Sid number</th>
      <th>Fbi number</th>
      <th>Oid number</th>
      <th>Afis number</th>
      <th>Ins number</th>
      <th>Email address</th>
      <th>Dna status</th>
      <th>Dna effective date</th>
      <th>Supervision sheet</th>
      <th>Client label</th>
      <th>Drivers license number</th>
      <th>Drivers license state</th>
      <th>Supervising location</th>
      <th>Supervising county</th>
      <th>Client status</th>
      <th>Effective date</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.first_name %></td>
        <td><%= client.middle_name %></td>
        <td><%= client.last_name %></td>
        <td><%= client.suffix_name %></td>
        <td><%= client.date_of_birth %></td>
        <td><%= client.age %></td>
        <td><%= client.ssn %></td>
        <td><%= client.adult %></td>
        <td><%= client.gender %></td>
        <td><%= client.county %></td>
        <td><%= client.citizen %></td>
        <td><%= client.marital_status %></td>
        <td><%= client.supervision_level_id %></td>
        <td><%= client.risk_level_id %></td>
        <td><%= client.sid_number %></td>
        <td><%= client.fbi_number %></td>
        <td><%= client.oid_number %></td>
        <td><%= client.afis_number %></td>
        <td><%= client.ins_number %></td>
        <td><%= client.email_address %></td>
        <td><%= client.dna_status_id %></td>
        <td><%= client.dna_effective_date %></td>
        <td><%= client.supervision_sheet %></td>
        <td><%= client.client_label %></td>
        <td><%= client.drivers_license_number %></td>
        <td><%= client.drivers_license_state_id %></td>
        <td><%= client.supervising_location %></td>
        <td><%= client.supervising_county %></td>
        <td><%= client.client_status_id %></td>
        <td><%= client.effective_date %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @client.first_name %>
</p>

<p>
  <strong>Middle name:</strong>
  <%= @client.middle_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @client.last_name %>
</p>

<p>
  <strong>Suffix name:</strong>
  <%= @client.suffix_name %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @client.date_of_birth %>
</p>

<p>
  <strong>Age:</strong>
  <%= @client.age %>
</p>

<p>
  <strong>Ssn:</strong>
  <%= @client.ssn %>
</p>

<p>
  <strong>Adult:</strong>
  <%= @client.adult %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @client.gender %>
</p>

<p>
  <strong>County:</strong>
  <%= @client.county %>
</p>

<p>
  <strong>Citizen:</strong>
  <%= @client.citizen %>
</p>

<p>
  <strong>Marital status:</strong>
  <%= @client.marital_status %>
</p>

<p>
  <strong>Supervision level:</strong>
  <%= @client.supervision_level_id %>
</p>

<p>
  <strong>Risk level:</strong>
  <%= @client.risk_level_id %>
</p>

<p>
  <strong>Sid number:</strong>
  <%= @client.sid_number %>
</p>

<p>
  <strong>Fbi number:</strong>
  <%= @client.fbi_number %>
</p>

<p>
  <strong>Oid number:</strong>
  <%= @client.oid_number %>
</p>

<p>
  <strong>Afis number:</strong>
  <%= @client.afis_number %>
</p>

<p>
  <strong>Ins number:</strong>
  <%= @client.ins_number %>
</p>

<p>
  <strong>Email address:</strong>
  <%= @client.email_address %>
</p>

<p>
  <strong>Dna status:</strong>
  <%= @client.dna_status_id %>
</p>

<p>
  <strong>Dna effective date:</strong>
  <%= @client.dna_effective_date %>
</p>

<p>
  <strong>Supervision sheet:</strong>
  <%= @client.supervision_sheet %>
</p>

<p>
  <strong>Client label:</strong>
  <%= @client.client_label %>
</p>

<p>
  <strong>Drivers license number:</strong>
  <%= @client.drivers_license_number %>
</p>

<p>
  <strong>Drivers license state:</strong>
  <%= @client.drivers_license_state_id %>
</p>

<p>
  <strong>Supervising location:</strong>
  <%= @client.supervising_location %>
</p>

<p>
  <strong>Supervising county:</strong>
  <%= @client.supervising_county %>
</p>

<p>
  <strong>Client status:</strong>
  <%= @client.client_status_id %>
</p>

<p>
  <strong>Effective date:</strong>
  <%= @client.effective_date %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Management</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div id="main-container" class="container">
      <div class="row">
        <div id="sidebar" class="col-xs-3">
          <h1>THis is the side bar</h1>
        </div>
        <div id="content" class="col-xs-9">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>